### ISSUE TITLE
Meta data per blog post?

### ISSUE THREAD

**Issue by stolencrown** [Shazwazza/Articulate#109]
Hi there! 
Does the articulate blog have functionality that allows for meta data per blog post?
 Like i want individual descriptions/keywords per blog post and I'm not seeing that functionality. 
If anyone has a work-around please feel free to speak up. 
Any help on this would be fantastic. Thanks again.

**Comment by Shazwazza** [comment]
Hi, yes of course you can add whatever additional fields you would like to a blog post. Since this is Umbraco you have full control over what happens. Articulate creates 3 document types for blog posts with this hierarchy:

![image](https://cloud.githubusercontent.com/assets/1742685/10536986/6c1d33f8-73ef-11e5-8453-7b29468de991.png)

If you want to add additional metadata to a blog post then edit the Articulate Post document type and add whatever fields you want.

The Model that Articulate uses is `Articulate.Models.PostModel`, this model implements the standard Umbraco `IPublishedContent` interface, so to access your custom property values you'd access them the traditional Umbraco way: https://our.umbraco.org/documentation/Getting-Started/Design/Rendering-Content/

**Comment by stolencrown** [comment]
so would i edit the master file of the blog to put something like  
<title>@Umbraco.Field("title")</title> 
then edit the document type accordingly? 

I tried that and I get a error 
"CS0234: The type or namespace name 'Field' does not exist in the namespace 'Umbraco' (are you missing an assembly reference?)" 

Thanks for the help!
