### ISSUE TITLE
Lazy loading feature instead of pagination.

### ISSUE THREAD

**Issue by NikhilPrajapati** [Shazwazza/Articulate#131]
Hi Guys.

Hope you are doing a great job!

Actually i would like to implement the lazy loading for blog posts while the user scrolls instead of Pagination.
So, Can you please explain me how can i do this ?
Awaiting Response!

Thank you!

**Comment by Shazwazza** [comment]
Hi there, you'd need to create a REST endpoint to retrieve the content information you require when you are lazy loading content. For the REST endpoint, you could easily create this yourself by creating a custom UmbracoApiController with an action that accepts a page number & page size and then in your Action you can perform the standard Umbraco published content lookups + Linq to query/page and return IPublishedContent instances. How you would consume and render this data would be up to you. 

You could just use the Umbraco RestApi project - though it might be easier to just create your own simple endpoint. You can see the Umbraco RestApi project code: 
* IPublishedContent action to return a paged search: 
     * some docs on the RestApi project: https://github.com/umbraco/UmbracoRestApi
     * https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Controllers/UmbracoHalController.cs#L57
     * The implementation of PerformSearch: https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Controllers/UmbracoHalController.cs#L57: 
https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Controllers/PublishedContentController.cs#L57
* The QueryStructure model to send to this endpoint: https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Models/QueryStructure.cs#L19

Just be aware that if you do this, you'd probably still want to have the paging links in your HTML so that the pages can still be indexed by search engines.

**Comment by NikhilPrajapati** [comment]
Aha...
Thank you.
I will dive into it for sure.
