### ISSUE TITLE
Pre styles broken in Markdown editor

### ISSUE THREAD

**Issue by JimBobSquarePants** [Shazwazza/Articulate#140]
Version 2.0.1

By default code samples rendered in the markdown editor preview are removing any word wrapping thus rendering the entire code sample on a single line.

I've had a dig around and it appears that the articulate markdown editor is a wrapper for the umbraco markdown editor. 

Should I be raising a ticket in the Umbraco issue tracker?

**Comment by Shazwazza** [comment]
Hrm, maybe. I think originally the markdown editor wasn't in the core so i put it in here and then now we ship with it in the core. If you can replicate the issue with Umbraco's normal MD editor then maybe yeah log a bug there. If it can be fixed in this repo for the time being though, i'm happy to do that.

**Comment by JimBobSquarePants** [comment]
I don't think we can unless there's a way to insert extra stylesheets in with your editor override. I'd love to replace the core one with a commonmark implementation to be honest so there was some standardisation.

**Comment by Shazwazza** [comment]
The core one was just chucked in there IIRC so would defo be good to get a better, more robust implementation in there.

**Comment by JimBobSquarePants** [comment]
Ace... Will look into it.

**Comment by JimBobSquarePants** [comment]
I fixed this in Umbraco at the CodeGarden retreat so we can close this.
