### ISSUE TITLE
Search only finds Posts in the archive

### ISSUE THREAD

**Issue by RythmDev** [Shazwazza/Articulate#146]
Hi,

I ran into an issue where using built in search with Articulate only return posts within the root 'Articulate Archive' folder. Are there any plans in the near future to revise the search functionality to find all blog posts including ones outside the default 'Articulate Archive' or within a custom archive?

Thanks

**Comment by Shazwazza** [comment]
The built in search template just calls the built in search endpoint for Articulate, by design this will only search the current archive.

If you want the functionality you've listed above, there is nothing stopping you from creating your own page/endpoint for running an Umbraco search to search any/all Umbraco content. 

There are no future plans for Articulate to be updated to support searching all archives OOTB with it's built in search controller as this would require all sorts of configuration options since this would not be ideal for many users.
