### ISSUE TITLE
Nuget package creation

### ISSUE THREAD

**Issue by hyrmedia** [Shazwazza/Articulate#147]
Is this still planned?

**Comment by Shazwazza** [comment]
This will not be possible until we have the concept of Package Migrations in place for Umbraco. I could hack that type of functionality in but I'd rather not.

**Comment by hyrmedia** [comment]
Interesting, could you elaborate on this? Why would this be a requirement to nuget-ize Articulate?

**Comment by Shazwazza** [comment]
Hi,

Articulate requires that specific document type structures are setup in the correct manner. The only way to install that data currently is when the site is running which is done using the umbraco packager. Articulate then will install the default blog site, this part especially requires that Umbraco has a web context due to some legacy ways the umbraco runs in order to publish content - this part is done when you finish the package installation and it shows the Articulate screen.

Currently there is no way to install any Umbraco data using Nuget, it's on the Umbraco road map for something called Package Migrations which will allow us to streamline data installation procedures for packages so they are the same regardless of if they are nuget packages or umbraco packages.

In the interim, yes I could release Articulate as a Nuget package, it would just mean developers have to manually install all of the data in a very specific way. Alternatively I could have a dashboard in the developer section installed that would do this. However, my time currently is super limited and I've always wanted a way to streamline the installation process between nuget and umbraco packages so package migrations are the way to do that.  Depending on how much time I have (chances are low), i could create a Nuget package with a dashboard installer, otherwise it will have to wait until package migrations are a reality.

As always though, I'd be super thrilled to receive a PR to make this happen, if you are interested please let me know as I have a standard build script that I use to produce these types of packages.

**Comment by hyrmedia** [comment]
That makes sense, but have you looked at the Umbraco Migrations system yet?
https://cultiv.nl/blog/using-umbraco-migrations-to-deploy-changes/

Looks like migrations (7.3.x+) get executed then stored in the DB so they don't get executed again. This lets you install install whatever data you like the first time the plugin code executes, via the `Up()` method. And as long as you do a check first inside the `Up()` method to make sure your data doesn't already exist, it shouldn't interfere with future uninstall/reinstalls, either.

I don't know if this is something I'll have time to tackle, but I might give it a shot if you really can't afford to.

**Comment by Shazwazza** [comment]
Yes Im definitely aware of that, but it's a hack, it doesn't cater for proper start-up, error handling etc, Also during start-up the web context isn't available so you cannot publish items correctly. Package migrations will eventually be done properly in the core, which will use migrations but be executed with an installer.

**Comment by Shazwazza** [comment]
Going to re-open this issue for now. 

Until package Migrations is in the core (probably 7.6) I can look at releasing a Nuget package that will include:

* a readme with information about installing the data
* update to the Articulate User Control custom installer - so the user presses a button to install the data instead of automatically
* update to the Articulate dashboard to link to the custom installer page (user control) so the user can install the initial data
