### ISSUE TITLE
How to use ONLY the slug for the post path?

### ISSUE THREAD

**Issue by hyrmedia** [Shazwazza/Articulate#148]
My Articulate blog is setup on a subdomain: `http://blog.mysite.com/`

I'd like to override the Articulate's routing to remove the `archive` portion of the URL, in order to achieve the following:
`http://blog.mysite.com/my-post-slug`

**Q: Is this possible? How might I achieve this?**

---

Note: I knew this was a stab in the dark, but I did try the new [VirtualNodes](https://github.com/sotirisf/Umbraco-VirtualNodes) package by Sotiris Filippidis (@sotirisf), attempting to make `ArticulateArchive` a "virtual node". It's a neat plugin, but Articulate's own rules seem to take precedence.

**Comment by quotewizard** [comment]
I second this request -- is it possible now?

**Comment by Shazwazza** [comment]
The only way this would be possible would be to either have url rewriting rules applied - which would be very difficult considering it could be any root page. Or you could try to create a custom IContentFinder for this to work. The reality is that the blog posts are Umbraco pages, they are not 'routed' pages, so their URLs are based on Umbraco's content hierarchy.

**Comment by quotewizard** [comment]
10-4, thanks for the response!

**Comment by Shazwazza** [comment]
One way this could be acheived is to add a text property to the articulatePost doc type called `umbracoUrlAlias` which is an Umbraco reserved name https://our.umbraco.com/Documentation/Reference/Routing/routing-properties and then use an event handler (ContentService.Saving) to update this text field with the full path that you want it routed too. It's not perfect since now your post will have multiple URLs but you could probably solve that with Url rewriting too.
