### ISSUE TITLE
How to change default size for blog post images

### ISSUE THREAD

**Issue by claire-james-infotrack** [Shazwazza/Articulate#157]
Hi,

Currently for all blog post images, they are automatically cropped to 200x200px and 50x50px. I have moved their location to take up the width of the post, but would like them not to be cropped (as they are now blurry and a square is not the desired shape). Could you please advise how to remove this auto-cropping?

Many thanks.

**Comment by Shazwazza** [comment]
Images are just set based on the image cropper definition, but you can set this to whatever you want. In the themes that ship with Articulate you'll see the code:

`var cropUrl = Model.GetCropUrl("postImage", "blogPost");`

which is used to render the blog post image. There is a bit of docs regarding this here (but it's not much); https://our.umbraco.org/Documentation/Getting-Started/Design/Rendering-Media/#rendering-media-item-with-image-cropper

The crop name 'blogPost' is defined at the data type level, Articulate uses it's own data type for this called "Articulate Cropper". There you can define any crop name + size or adjust the default ones set.

However, you have a ton of flexibility for rendering cropped images, Articulate just happens to use a named crop but you don't need to do that at all. The `GetCropUrl` method has a ton of overloads: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/UrlHelperRenderExtensions.cs#L18

You'll note that the code Articulate uses is deprecated code, instead of `var cropUrl = Model.GetCropUrl("postImage", "blogPost");`, it should be doing this:

`var cropUrl = Url.GetCropUrl(Model, "postImage", "blogPost")`

If you wanted to pass in any arbitrary crop size you could do something like (if you wanted to auto-size height):

`var cropUrl = Url.GetCropUrl(Model, propertyAlias: "postImage", width: 800)`

The link to all of the GetCropUrl overloads will give you an idea of what is possible.

**Comment by Shazwazza** [comment]
Ahh, found the other docs about image cropping here: https://our.umbraco.org/documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Image-Cropper
