### ISSUE TITLE
Error in PostModel after upgrading to 7.6.0 - GetPropertyValue<string> returns "System.String[]"

### ISSUE THREAD

**Issue by GeorgDangl** [Shazwazza/Articulate#231]
So, I just upgraded my blog to 7.6.0 and noticed that tags and categories in the [PostModel](https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/Models/PostModel.cs#L32-L48) are not being deserialized correctly:
![articulatetagserror](https://cloud.githubusercontent.com/assets/10274404/25681827/09f765fc-3056-11e7-8d5c-809495f856f2.PNG)

It seems that `public static T GetPropertyValue<T>(this IPublishedContent content, string alias)` was changed to return the `.ToString()` method of the already parsed array (Umbraco no longer returns a comma separated string).

## Fix for now:
```cshtml
@{
    var categories = Model.GetPropertyValue<IEnumerable<string>>("categories");
    if (categories != null)
    {
        var categoriesList = categories.ToList();
        foreach (var category in categoriesList)
        {
            <a href="@Url.ArticulateCategoryUrl(Model, category)">@category</a>
            if (category != categoriesList.Last())
            {
                <span>, </span>
            } 
        }
    }
}
```

Use `Model.GetPropertyValue<IEnumerable<string>>("categories")` (or `tags`) instead of `Model.Tags` or `Model.Categories`.

## My Setup
I've installed Articulate as local package on my local machine, then referenced the required dlls as project dependency, included the `App_plugins/Articulate` folder in source control and used uSync to sync to my blog. It's not being displayed as installed package, but everything has been working fine for about a year now.

## FYI:
I've noticed that there have also been changes to how `MediaPicker` properties are returned.
`GetPropertyValue<int>("profilePicture")` did no longer return the id of the media item, so I had to use
 `this.GetPropertyValue<IPublishedContent>("profilePicture").Id`. I'm not sure if this is used somewhere in Articulate, but it might be of interest and related to this issue.

**Comment by Shazwazza** [comment]
This might be due to the new property value converters, you can try to disable them and see what happens (they will be disabled by default for Upgrades, but for new installations they are enabled by default)

http://issues.umbraco.org/issue/U4-7318 

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7.6/src/Umbraco.Web.UI/config/umbracoSettings.Release.config#L60


This is odd because my own site is running 7.6 and works fine

**Comment by GeorgDangl** [comment]
I think that's the reason, the git diff shows the following for the upgrade:
```
+    <!-- Enables value converters for all built in property editors so that they return strongly typed object, recommended for use with Models Builder -->
+    <EnablePropertyValueConverters>true</EnablePropertyValueConverters>
```

This happened via NuGet upgrade from 7.5.8 to 7.6.0. When I'm upgrading, I usually select *Yes* when asked about overwriting existing files. Should one click *No* there?

**Comment by Shazwazza** [comment]
Yes always answer NO https://our.umbraco.org/documentation/Getting-Started/Setup/Upgrading/general#are-you-using-nuget

**Comment by GeorgDangl** [comment]
Thank you, that's now much clearer!

**Comment by ToadSageNaruto** [comment]
Hello,

I am also experiencing the same error of tags and categories with umbraco 7.6.3. Not sure how to address this issue. Any help is appreciated
![capture](https://user-images.githubusercontent.com/17419967/28036034-baeb0e8c-6584-11e7-9aaa-87476977ebf3.PNG)

**Comment by simonech** [comment]
Which version of articulate and which (exact) of Umbraco?

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 10 July 2017 at 21:31:33, ToadSageNaruto (notifications@github.com)
wrote:

Hello,

I am also experiencing the same error of tags and categories with umbraco
7.6.3. Not sure how to address this issue. Any help is appreciated
[image: capture]
<https://user-images.githubusercontent.com/17419967/28036034-baeb0e8c-6584-11e7-9aaa-87476977ebf3.PNG>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shazwazza/Articulate/issues/231#issuecomment-314210444>,
or mute the thread

**Comment by ToadSageNaruto** [comment]
I am using umbraco 7.6.3 and Articulate 2.0.5

**Comment by ToadSageNaruto** [comment]
I'm using umbraco 7.6.3 and articulate 2.0.5

**Comment by ToadSageNaruto** [comment]
I'm using Articulate 2.0.5, which I got from installing via umbraco back office packages. Is there a newer Articulate package available from umbraco backoffice?

**Comment by Shazwazza** [comment]
3.0 isn't released yet

**Comment by ToadSageNaruto** [comment]
I see. Is there a way I can manually create the updated Articulate package from the Articulate-master solution? I tried following the contributing section on 

https://github.com/Shazwazza/Articulate 

But wasn't too successful due to missing directive or assembly error from the ThemeEditorContoller.cs

"GetTreePathFromFilePath" and "CreateFolder". Would you by chance know why those function calls are missing a reference? Thank you for your time.

**Comment by ToadSageNaruto** [comment]
Hello Gents,

I got the latest from "Articulate-master" and was able to create the newer Articulate package. Thank you all for your assistance.
