### ISSUE TITLE
How do I export Blog Entries (including media) to blogml

### ISSUE THREAD

**Issue by dyardyGIT** [Shazwazza/Articulate#252]
I have been using umbraco + articulate blog engine.  How do I go about export blog entries to neutral xml/json format?
thx

**Comment by simonech** [comment]
You can access the export from the dashboard on the developer section.
But AFAIK it doesn't export embedded media objects 
Simone

**Comment by dyardyGIT** [comment]
I have an earlier version of articulate and I don't think the export existed in this release 1.x.  I am working on trying to upgrade the articular version, however not sure how to do this ..any ideas? (i have the umbraco+articulate open in vs.net) i have downloaded articulate but not sure how to merge/update these.

ideas
thx

**Comment by simonech** [comment]
Just update the package to latest version and upgrade should happen
automatically

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 29 May 2017 at 18:52:38, dyardyGIT (notifications@github.com) wrote:

I have an earlier version of articulate and I don't think the export
existed in this release 1.x. I am working on trying to upgrade the
articular version, however not sure how to do this ..any ideas? (i have the
umbraco+articulate open in vs.net) i have downloaded articulate but not
sure how to merge/update these.

ideas
thx

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Shazwazza/Articulate/issues/252#issuecomment-304700122>,
or mute the thread

**Comment by dyardyGIT** [comment]
Yes ...i updated and it appears i am running the latest now.. Easier than expected.  Now "dashboard on the developer" ...where might i find this? 
I am on the developer page - where i see getting started, examine management, xml data integrity, articulate importer..but nothing yet about export.

**Comment by simonech** [comment]
The import has an export button too :)

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 29 May 2017 at 19:01:36, dyardyGIT (notifications@github.com) wrote:

Yes ...i updated and it appears i am running the latest now.. Easier than
expected. Now "dashboard on the developer" ...where might i find this?
I am on the developer page - where i see getting started, examine
management, xml data integrity, articulate importer..but nothing yet about
export.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shazwazza/Articulate/issues/252#issuecomment-304701232>,
or mute the thread

**Comment by dyardyGIT** [comment]
Hmm I don't see it
![2017-05-29_13-05-08](https://cloud.githubusercontent.com/assets/3586830/26557455/8ebac1c6-446f-11e7-9ece-9adee962be05.jpg)

**Comment by simonech** [comment]
It doesn’t look like the UI of the latest version. Try clearing the cache
of your browser


-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 29 May 2017 at 19:06:01, dyardyGIT (notifications@github.com) wrote:

Hmm I don't see it
[image: 2017-05-29_13-05-08]
<https://cloud.githubusercontent.com/assets/3586830/26557455/8ebac1c6-446f-11e7-9ece-9adee962be05.jpg>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shazwazza/Articulate/issues/252#issuecomment-304701858>,
or mute the thread

**Comment by dyardyGIT** [comment]
Great thank you!
