### ISSUE TITLE
Auto publish to social media

### ISSUE THREAD

**Issue by Lukejkw** [Shazwazza/Articulate#257]
Wordpress has a feature whereby when you publish an article you can auto publish a link to the article to Facebook, Twitter and/or LinkedIn.

I am willing to work on and contribute this feature should it be something you think would add value. Otherwise, I will just build it into my own blog instance.

Thoughts?

**Comment by simonech** [comment]
I think there is already a package that does that.
You could combine the two packages without baking it directly into
Articulate.

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 8 June 2017 at 11:02:45, Luke Warren (notifications@github.com) wrote:

Wordpress has a feature whereby when you publish an article you can auto
publish said article to Facebook, Twitter and/or LinkedIn.

I am willing to work on and contribute this feature should it be something
you think would add value. Otherwise, I will just build it into my own blog
instance.

Thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shazwazza/Articulate/issues/257>, or mute the thread

**Comment by Lukejkw** [comment]
That sounds good.

Do you have a link to the package? Can't seem to find anything.

**Comment by simonech** [comment]
cant remember right now. social something

**Comment by Lukejkw** [comment]
I think it is this one: https://our.umbraco.org/projects/website-utilities/ushare/

I will test to see if it is still compatible. I agree that using this would be a better option.

**Comment by simonech** [comment]
@Lukejkw have you had any luck with uShare?

**Comment by Lukejkw** [comment]
@simonech 

I gave it a go a while back and it worked fine from memory.

Maybe post on the Our forums to get feedback from others?

**Comment by simonech** [comment]
@Lukejkw apparently uShare doesn't work anymore due to some changes in Facebook APIs.

**Comment by Shazwazza** [comment]
Hi, I think this functionality is suited to exist outside of Articulate since it's really more of a generic feature that can be done with Umbraco.
