### ISSUE TITLE
access the list of categories from other view besides Tags.cshtml?

### ISSUE THREAD

**Issue by boris21g** [Shazwazza/Articulate#280]
Hello, 
I need to show a list of all the categories in the home page and post the post pages, how can i access it?

**Comment by Shazwazza** [comment]
Categories are Tags. You can use the UmbracoHelper.TagQuery (`ITagQuery`) APIs to query these.

https://our.umbraco.org/apidocs/csharp/api/Umbraco.Web.ITagQuery.html

for example:

`Umbraco.TagQuery.GetAllContentTags("ArticulateCategories")`

since "ArticulateCategories" is the tag category used for Articulate Categories
