### ISSUE TITLE
Url.ArticulateCategoryUrl(Model, c) generating whitespace.

### ISSUE THREAD

**Issue by GiraffeCoding** [Shazwazza/Articulate#282]
Sitemap crawlers are indexing the URL's generated by Url.ArticulateCategoryUrl with white space which is causing google searches to index the wrong pages.

So for example the following:
/blog/categories/Event of the week

is being indexed as:
/blog/categories/event%20of%20the%20week/

Is there anyway around this?

**Comment by Shazwazza** [comment]
Hi,

What is the Umbraco and Articulate version you are using?

**Comment by Ben-TangentDesign** [comment]
Umbraco version 7.5.4 assembly: 1.0.6136.27241

Articulate 2.0.5

**Comment by simonech** [comment]
That’s an old version of articulate. Can you try upgrading to v3?
Thx

**Comment by Ben-TangentDesign** [comment]
Hi,

That version isn't compatible with the Umbraco currently installed. We can't upgrade the version due to other package requirements at this time.

**Comment by Ben-TangentDesign** [comment]
Hi,

I've upgraded to version 3.0.1 and its still producing the same issue. 
Is there no way to have this as hyphens instead of whitespace?

Thanks in advance for your help.

**Comment by Shazwazza** [comment]
Hi, so what is the actual problem with whitespace in the URLs? 

The underlying problem with changing the URL for a tag/category is the tag/category exists as-is in the Umbraco database. So it is stored as "Event of the week" which is also how it needs to be looked up. 

In order to change a string with spaces or special chars to something nicer for URLs means we also need to fail safe way to convert it back to the actual string value. This can prove quite difficult since there will be all sorts of escaping logic needed. The way tags/categories are stored is done by Umbraco, not Articulate, so Articulate doesn't have some extra storage space to store a tag's URL name to a tag's actual name. To do this would require a custom database table managed by Articulate.

**Comment by Shazwazza** [comment]
Hi, so what is the actual problem with whitespace in the URLs? Is it just a cosmetic thing?

We can have a config option to turn spaces to hyphens (or something else) but this will cause problems if there is a hyphen in the tag name itself. I could make this an optional configuration thing but know that it would break things if the delimiter is used in any tag name.

**Comment by GiraffeCoding** [comment]
It was a purely cosmetic request from the client that they claimed was causing issues with their seo. It was basically causing google to index the pages with '%20%'.

This was apparently effecting the search results but I was yet to see convincing results from this other than a seo company complaining it was knocking the client off top spots in search results.

**Comment by lcichanowicz** [comment]
I am using Articulate 3.0.2 with Umbraco 7.14.0 and I have found that tags and categories do not either replace the spaces with dashes, as is common, or URL encode it.  It seems Articulate should do one or the other.  It would be a nice touch to add a filed in the "root" Blog node, on the Customize tab to configure this.

**Comment by Shazwazza** [comment]
@lcichanowicz replacing spaces with dashes is problematic because we need to decode that too. I'm sure there's probably a clever way but if your tag also contains dashes, how would you know which dashes to change back to spaces? You'd have to convert the dashes to something as well, but then this problem continues because what if that 'something' is also used in tag.

The URLs mentioned above are URL encoded but let me know if you are seeing other things.
