### ISSUE TITLE
Enabling cache

### ISSUE THREAD

**Issue by MarkyYeah** [Shazwazza/Articulate#310]
Hi, does anyone know if it is possible to cache blog pages? Or use OutputCache somehow, etc?

Thanks

Mark

**Comment by Shazwazza** [comment]
The rendering of blog posts is done by articulate controllers which perform Umbraco route hijacking. These controllers are: [ArticulateRichTextController](https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/Controllers/ArticulateRichTextController.cs) and [ArticulateMarkdownController](https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/Controllers/ArticulateMarkdownController.cs)

If you wanted to add actual OutputCache to these controllers, there's a couple ways you could go about it:

### Custom global filter

Create a custom OutputCacheAttribute class that inherits from `System.Web.Mvc.OutputCacheAttribute` and then override both `OnActionExecuting` and `OnActionExecuted`. In these 2 methods you'd check if the controller executing is either ArticulateRichTextController or ArticulateMarkdownController and if not, then exit. This means that this class will only execute for these 2 controllers types. Then you can add this class to the MVC global filters on startup like `GlobalFilters.Filters.Add(new MyArticulateOutputCacheAttribute());` . You could probably pass in custom ctor arguments to it to modify the output cache params

### Custom controller factory

You could create 2 custom controllers that inherit from ArticulateRichTextController and ArticulateMarkdownController and add the normal [OutputCache] attribute to these, then you would need to make sure your own custom controllers are used when executing instead of Articulate's ones. To do that i think you would need to create a custom controller factory. You'd create a class that inherits from `UmbracoControllerFactory`. Then override the `CanHandle` method and you would only return true if the request is for these 2 controller types ... i think you can check for this in the `request.RouteData` but not sure. Then you would override `GetControllerType` and return your own types for these controllers instead of articualte's. Then on ApplicationStarting you would need to add your custom controller factory like `FilteredControllerFactoriesResolver.Current.InsertType<MyCustomControllerFactory>(0);`

### Partial view cache

The easiest way to 'cache' a blog post page however that isn't using true OutputCache would be to just use the @Html.CachedPartial call in your Articulate's theme file `Post.cshtml` and put all of your blog post markup inside of a partial view instead of inside Post.cshtml

Of course this doesn't give you the full power of OutputCaching but might do what you want, just depends on what your caching requirements are.

**Comment by MarkyYeah** [comment]
Thank you very much, just what I needed!
