### ISSUE TITLE
Best Strategy for multilingual & multi-tenancy website

### ISSUE THREAD

**Issue by khraibani** [Shazwazza/Articulate#368]
Hi @Shazwazza I am working on a multi-tenant Umbraco project, we are handling multi-lingual by using language variants. all sitting underneath the same domain name.

- Each subsite will by managed by a content editor across the globe
- The Global site will have a blog in English
- Each subsite (Might have a blog) 
- Blog on subsite can be in English and/or different language(s) - Does language variant works? or do we need to have an  archive per variant.
- Subsite editor have no access to the Global node.
- The subsite are for in-country firms so its not a replica of the Global site.
- We have about 34 subsites ( not all them require a blog)
- A Blog engine for each subsite or 1 blog engine shared among all sites? 
- How do we handle categories/tagging for it to be only for the current site for example if we have 1 single blog engine
Site 1: tag 1 - only show post that belong to the current site even if the same tag exist on another blog. 

What is the best strategy for adding a blog to cater for the above requirements.

Any recommendation would much appreciate it.

Umbraco ver:8.14.1
![Screenshot 2021-08-12 124722](https://user-images.githubusercontent.com/4085627/129191789-ce224d36-8a6a-4945-a94a-ed8d1f36a58d.png)

Many Thanks!

**Comment by Shazwazza** [comment]
Hi,

Articulate just uses standard Umbraco nodes and recent releases make it support language variants too. I haven't pushed this to its limits so I'm unsure if any issues exist with content variants and Articulate but it should all work. As for using the traditional way of multi-lingual where you have a different branch per language, Articulate would work no problem with that since that is the old traditional way of working and there's no magic going on there. So as far as I know, Articulate will work with language variants just like any other Umbraco node would. All I can suggest is that you test this and see what happens. 

Hope that helps.

**Comment by Shazwazza** [comment]
As for categories, tagging, etc... Articulate just uses Umbraco's tag functionality.

**Comment by khraibani** [comment]
@Shazwazza thank you!
I am using the old way of handling multi-lingual as each site isn't a replica of the Global one, and they differ. We are trying to organise a company that have 35 different domain all sharing similar functionality but very fragmented from brand perspective😅
So you think it should be ok, to have a blog node under each subsite? 
I will do some testing a feedback.

Many Thanks again!

**Comment by Shazwazza** [comment]
Yep sure having an articulate node under each subsite with traditional multi-lingual trees will work fine.
