### ISSUE TITLE
Issues while editing CSS of the blog

### ISSUE THREAD

**Issue by sangeeta-singh-github** [Shazwazza/Articulate#452]
Hi,
I'm trying to edit css of the blog which is using vapor them (Default theme) However, unable to to see them when running the blog. Here's what I tried:

I opened skin.css file which is inside vapor folder of the articuate project and edited certain css rules, saved file, refreshed the page.
Didn't see the changes. 

Also, tried to delete the temp folder inside the umbraco folder which indeed reverted all the changes I had applied to css files? Don't know why?

Also the css path on the page is a not actual location I guess it is virtual. 

How can I edit css of the blog like normal sites and not lose any changes that I did?

I'm using umbraco 13 and this is the first plug in I have installed.

Please suggest.

**Comment by sangeeta-singh-github** [comment]
Hi @Shazwazza any view on my issue?

**Comment by gavinfaux** [comment]
Have your tried using the back office Articulate tab to create a copy of the theme and then editing your new named theme in the /Views/ArticulateThemes/yourtheme folder? 

We run a v10 site (same code base as 13) and have no issues with theme/CSS (we just change our theme master layout to include site CSS rather than separate blog CSS, but either or/both works, it's just CSS).

Are you running in debug/development mode? Changes should be picked up immediately, if your in release/production mode you may need to restart worker process or see https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/reference/configuration/runtimeminificationsettings if using Smidge.

*edited to correct theme folder location

**Comment by Shazwazza** [comment]
@sangeeta-singh-github 
You cannot edit existing templates. They are all embedded resources, etc... Like @gavinfaux says, if you want to edit templates, you need to make copies by following his suggestions via the back office. Once they are copied to a name of your choice then you can edit the files in the file system like normal views. The copying I don't think copies the CSS/JS files since they are still referenced in bundles, so you would need to manually do that work. I think there's another Github issue/topic about that that you can find in this repo too.
