### ISSUE TITLE
Making the paging SEO friendly

### ISSUE THREAD

**Issue by shoecake** [Shazwazza/Articulate#56]
I have partially created an update so the paging will be more seo friendly. I have modified the code to create urls in the format:

http://www.domainname.com/blog/page/2
http://www.domainname.com/blog/categories/CategoryName/page/2
instead of
http://www.domainname.com/blog?p=2

but I cannot see how to modify the routing within articulate. For now I have created a URL rewrite rule. 

Modifications are in the attached images.

![spc articulate changes to make seo friendly](https://cloud.githubusercontent.com/assets/8297265/6091868/a5bfa476-aeb8-11e4-9658-865462dd979b.PNG)

![spc articulate changes to make seo friendly rewrite rules](https://cloud.githubusercontent.com/assets/8297265/6091871/edfa96e2-aeb8-11e4-998e-5f9615222e39.PNG)

**Comment by benediktvaldez** [comment]
+1 :)

**Comment by meixger** [comment]
could you explain why this would be more seo friendly?

**Comment by vincentparrett** [comment]
+10 static urls are better than dynamic ones from an seo point of view.

http://searchengineland.com/seo-friendly-url-syntax-practices-134218

http://www.wordtracker.com/academy/learn-seo/technical-guides/seo-clean-urls

**Comment by Shazwazza** [comment]
yes, clean URLs are great, and Articulate/Umbraco follow these rules, but there is a reason for query strings = for dynamically displayed content. Query strings for paging or searching isn't poor SEO because the content displayed for these pages is dynamic based on the query strings. That said it would be better SEO to have the query string parameter say 'page' instead of 'p'

It wouldn't be hard to change the paging and searching URLs to use paths instead but I actually think this is worse for SEO since this URL is less meaningful:

http://www.domainname.com/blog/page/2

than this:

http://www.domainname.com/blog?page=2

**Comment by vincentparrett** [comment]
Any chance to make it optional?

**Comment by Shazwazza** [comment]
Yeah, i'll keep this issue open and review when i get some time but happy for anyone else to implement this if they have time

**Comment by meixger** [comment]
I don't see any SEO advantages in using paths instead of query strings - on the contrary i prefer query strings on my sites.
However i suggest optimizing the paging url's - please see PR #99:
[...] Avoid duplicate content by redirect ?page=1 links. Don't generate links with ?page=1. [...]

**Comment by biapar** [comment]
+1

**Comment by Shazwazza** [comment]
I'm marking this as won't fix as I also agree that query strings are the correct approach. If necessary you can use rewrite rules if you don't agree. Thanks all.
