### ISSUE TITLE
Question about RSS Feed

### ISSUE THREAD

**Issue by naepalm** [Shazwazza/Articulate#71]
Hi Shannon! I changed the "Rich Text" articulate post on Skrift to actually use the gridview instead of the rich text editor which, I'm sure doesn't surprise you, broke the content for the RSS feed. What would you recommend I do to fix this? Should I just fork Articulate and build out a custom RSS feed or do you have a better solution? Thanks :)

**Comment by Shazwazza** [comment]
ah interesting, if you have time to fork and figure out how to make it work then by all means give it a go :) Otherwise when i get some time I can make the Articulate RSS feed thingy a bit more flexible so you can have more control over how the content is rendered.

Your other option is to just create a custom RSS feed at a custom URL and then set the custom RSS feed url in articulate to that one.

**Comment by naepalm** [comment]
It would be awesome if you made it more flexible in the long run, but
man... time, right? Both the options you suggested will work, so I'll use
one in the meantime. Thanks! :)

Janae Cram, Developer
Mindfly Studio
114 W Magnolia St, Suite 300
Bellingham, WA 98225
360.647.7470

**Comment by Shazwazza** [comment]
Time indeed... need more of it :)

**Comment by Shazwazza** [comment]
See comment on #44
