### ISSUE TITLE
Add an image to Post

### ISSUE THREAD

**Issue by vnbaaij** [Shazwazza/Articulate#80]
Hi,
In an implementation we are doing now, we added an image field (Articulate Cropper) to the Post doctype and an image property to the PostModel.
What do you think about adding this? Shall I make a pr?

**Comment by Shazwazza** [comment]
Thats fine if you want to have that in your own installation but i'd rather not ship with it since it will confuse people as to why it is there. Also Live Writer does not populate this field unless we were to update the live writer integration to save the first image found to that field. We'd also have to update one (or more) of the templates to display this image so that people would know what it is.

I'll leave this issue open and flag as an enhancement since if we do this, then i'd like all of the functionality in place.

**Comment by vnbaaij** [comment]
Ok, fine by me. That's why I asked here first and not made the PR right away

**Comment by Shazwazza** [comment]
This is now done, I'll post up some more documentation about this including upgrade instructions on next release. I've already added some docs on new options: https://github.com/Shazwazza/Articulate/wiki/Configuration#weblogoptions

**Comment by Shazwazza** [comment]
This is marked as a breaking change because it requires some manual upgrade steps:

## Upgrade steps:

* Create a new tab on the 'Articulate' Document type called "MetaWeblog options"
* Create a property on this new tab with the name: "*Extract First Image to Property*" and the alias: "*extractFirstImage*". The Type must be: "*True/False*", the description should be: "*When Windows Live Writer (or compatible WebBlog API tool) is used to create blog posts, with this option enabled it will set the first image found in the blog post to the blog's image property if one is found.*"
