### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by kershnerd** [Shazwazza/Articulate#85]
Is there a reason why new blog posts are created at the http://URL/archive/{slug}?

To me, it should be routed to:
http://URL/blog/{slug}

What is the reason for this?

**Comment by Shazwazza** [comment]
You can change the URLs very easily. It's called "Archive" because when looking at the tree structure in the back office, that makes sense and that is what I chose.

Any umbraco node can have it's default URL name changed using the Umbraco property called umbracoUrlName ... I can't remember if this is installed by default with Articulate or not, but you can easily just create it.

![image](https://cloud.githubusercontent.com/assets/1742685/8473200/cf17584e-20a7-11e5-94f7-19115d20b759.png)

Then you can just change the url name to whatever you want:

(For example, on  my blog, the 'archive' is called 'post': http://shazwazza.com/post/using-linqpad-with-umbraco/ )

![image](https://cloud.githubusercontent.com/assets/1742685/8473209/ef35caf2-20a7-11e5-8a84-5ea34cd62316.png)

**Comment by kershnerd** [comment]
Thank you!

**Comment by kershnerd** [comment]
I have my set up like this...
/blog/ is the URL to a summary of {pageSize} blog posts
/blog/{slug} is the URL to a specific blog post

The problem I am running into is that when I add a new blog post and publish, my original /blog/ route gives me this 404 error:
Page not found

No template exists to render the document at url '/blog'.

In addition, no template exists to render the custom 404.

This page can be replaced with a custom 404. Check the documentation for "custom 404".

This page is intentionally left ugly ;-)

-----------------------------------
Any idea what might be going wrong?

**Comment by Shazwazza** [comment]
Not sure, if  you can replicate the issue please provide steps

**Comment by MusicDemon** [comment]
I vouch for this problem.

The scenario is simple: Create a new instance of Umbraco, install Articulate either at root or subdirectory and navigate to Archive.

@Shazwazza I read multiple times you don't encounter this problem. I'm really uncertain why this is happening. _**Checked your site while writing....**_ However, your site is also suffering from this issue: http://shazwazza.com/post/ is a dead end. But http://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/ works without a problem, like for the rest of us.

This is the only record I can find in the logs: 

> [P4004/D2/T43] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.

Please ring back with any news or questions. I want to publish my site but this bug is... Bugging me. (pun intended.)

**Comment by Shazwazza** [comment]
What you are referring to about http://shazwazza.com/post/ is this issue: https://github.com/Shazwazza/Articulate/issues/213

you can easily work around this issue yourself, in 3.0.0 a redirect will be built in but you can add that now.
