### ISSUE TITLE
Creating a new Template

### ISSUE THREAD

**Issue by kershnerd** [Shazwazza/Articulate#87]
I have my own Master template with sub templates for each of my pages and this is working well.

Shouldn't I be able to create a blog template and assign the Document Type "Archive Article" to use that template?

When I do that now, I get this error:
No template exists to render the document at url '/blog'.

**Comment by Shazwazza** [comment]
That's not how Articulate works, it uses themes and all pages use Route Hijacking to take care of this. This is all documented: https://github.com/Shazwazza/Articulate/wiki
You can still do what you want to do with a shared master template, you just need to create a custom Articulate theme and each view just points to the virtual path of your normal master template. There's lots of discussion our our.umbraco.org about this too.

**Comment by kershnerd** [comment]
I am having a little trouble finding how to create a custom theme on our.umbraco.org.

But I am looking at your wiki under creating a theme.  So based on your first paragraph, I should copy an existing theme (for example "Shazwazza") and rename to a custom name.

Once I do that, I should be able to change the Theme in the Content->Blog under the Style tab (Theme dropdown).  Then I can just edit the views in the custom template.  Is that correct?  That seems pretty easy... 

The problem is that I don't want to create an new master template but rather re-use the existing one I have (that way if I make changes, I don't have to do it twice).  You mentioned that I can "create a custom Articulate theme and each view just points to the virtual path of your normal master template."  How do I accomplish this?

**Comment by Shazwazza** [comment]
Yup, so copy a theme, name the copied folder with a theme name  you want, then you can manipulate all of the views, etc... You can select the new theme from the drop down on the Articulate root.

If you want to share a master template from another folder, that is just an standard MVC thing, at the top of every view you tell it what master you want to use, example:

@{
    Layout = "Master.cshtml";
}

That path can be a virtual path like:

@{
    Layout = "~/Views/MyCoolMasterPage.cshtml";
}

*However*, you're master view must be the same model as the view that is using your master view, this is how MVC works. Articulate uses a model of type: IMasterModel which implements IPublishedContent which is the underlying model that Umbraco uses. So you should in most cases make the model of your master template to be IPublishedContent. There's a few  posts on the forum about this since seems to confuse people.

* https://our.umbraco.org/projects/starter-kits/articulate/discussions/63323-Other-page-types-together-with-the-Articuate-Blog
* https://our.umbraco.org/projects/starter-kits/articulate/discussions/54733-Articulate-integration-in-existing-site
